CREATE TABLE MATORD (
	MONUM	varchar2(100)	NULL,
	MICODE	varchar2(50)	NOT NULL,
	CSCODE	varchar2(50)	NOT NULL,
	REQNUM	varchar2(100)	NOT NULL,
	MOODATE	date	NULL,
	MORDATE	date	NULL,
	MOOAM	number	NULL,
	MOMATAM	number	NULL,
	MOASKAM	number	NULL,
	MOSTATUS	varchar2(20)	NULL
);

CREATE TABLE MATSAR (
	MSNUM	varchar2(100)	NOT NULL,
	MONUM	varchar2(100)	NULL,
	MLNUM	varchar2(100)	NULL,
	PCDNUM	varchar2(100)	NOT NULL,
	MSDATE	date	NULL,
	MSAM	number	NULL,
	MSDIV	number	NULL,
	MSNOTE	varchar2(400)	NULL
);

CREATE TABLE PRODPLAN (
	PPNUM	varchar2(100)	NOT NULL,
	PPDATE	date	NULL,
	PPNAME	varchar2(100)	NULL,
	PPSTATUS	varchar2(20)	NULL,
	PPNOTE	varchar2(1000)	NULL
);

CREATE TABLE PRODPLAN_D (
	PPDNUM	varchar2(100)	NOT NULL,
	PPNUM	varchar2(100)	NOT NULL,
	PRNUM	varchar2(100)	NOT NULL,
	GICODE	varchar2(50)	NULL,
	PPDAM	number	NULL,
	UPLAM	number	NULL,
	PPDDATE	 date	NULL
);

CREATE TABLE PRODCOMM (
	PCNUM	varchar2(100)	NOT NULL,
	PCDATE	date	NULL,
	PCNAME	varchar2(100)	NULL,
	PCSTATUS	varchar2(20)	NULL,
	PCNOTE	varchar2(1000)	NULL
);

CREATE TABLE PROCCOMM_D (
	PCDNUM	varchar2(100)	NOT NULL,
	PCNUM	varchar2(100)	NOT NULL,
	PICODEID	varchar2(50)	NOT NULL,
	PPDNUM	varchar2(100)	NULL,
	GICODE	varchar2(50)	NULL,
	PCDAM	number	NULL,
	PCDDIV	varchar2(20)	NULL,
	PCDSDATE	date	NULL,
	PCDEDATE	date	NULL,
	PCDKEEPER	varchar2(100)	NULL
);

CREATE TABLE MATREQ (
	REQNUM	varchar2(100)	NOT NULL,
	MICODE	varchar2(50)	NULL,
	MRREQAM	number	NULL
);

CREATE TABLE PROCHEAD (
	PHNUM	varchar2(100)	NOT NULL,
	PCDNUM	varchar2(100)	NOT NULL,
	PICODEID	varchar2(50)	NULL,
	PHDATE	date	NULL
);

CREATE TABLE PROCHEAD_D (
	PHDNUM	varchar2(100)	NOT NULL,
	PHNUM	varchar2(100)	NOT NULL,
	SINUM	varchar2(100)	NOT NULL,
	PHDSTIME	date	DEFAULT sysdate,
	PHDETIME	date	DEFAULT sysdate,
	PHDMKAM	number	NULL,
	PHDERRAM	number	NULL,
	PHDSTAT	varchar2(20)	NULL
);

CREATE TABLE GOODS_ERR (
	GENUM	varchar2(100)	NOT NULL,
	PHDNUM	varchar2(100)	NOT NULL,
	EICODEID	varchar2(50)	NOT NULL,
	GEDATE	date	NULL,
	GEDETAIL	varchar2(1000)	NULL,
	GICODE	varchar2(50)	NULL
);

CREATE TABLE SYSINFO (
	SINUM	varchar2(100)	NOT NULL,
	SIDATE	date	NULL,
	SIDIE	date	NULL,
	SIMAINT	date	NULL,
	SINAME	varchar2(100)	NULL
);

CREATE TABLE CONTRACT (
	CNNUM	varchar2(100)	NOT NULL,
	CNAM	number	NULL,
	CNREST	number	NULL,
	CNDATE	date	NULL,
	CNPERIOD	date	NULL,
	CSCODE	varchar2(50)	NOT NULL,
	GICODE	varchar2(50)	NOT NULL
);

CREATE TABLE PRODREQ (
	PRNUM	varchar2(100)	NOT NULL,
	CNNUM	varchar2(100)	NOT NULL,
	PRCLOSE	date	NULL,
	PRSTATUS	varchar2(1)	NULL
);

CREATE TABLE GOODSSTK (
	GICODE	varchar2(50)	NOT NULL,
	GSAM	number	NULL
);

CREATE TABLE SHIP (
	SHNUM	varchar2(100)	NOT NULL,
	CNNUM	varchar2(100)	NOT NULL,
	GICODE	varchar2(50)	NOT NULL,
	CSCODE	varchar2(50)	NULL,
	SHAM	number	NULL,
	SHDATE	date	NULL,
	SHSTATUS	varchar2(1)	NULL,
	SHDAM	number	NULL
);

CREATE TABLE SYSMAN (
	SMNUM	varchar2(100)	NULL,
	SINUM	varchar2(100)	NOT NULL,
	SMCONS	varchar2(100)	NULL,
	SMNEXDAT	date	NULL,
	SMSTATUS	varchar2(1)	NULL,
	SMOBJAM	number	NULL,
	SMSPEED	varchar2(20)	NULL,
	SMTMPMAN	number	NULL
);

CREATE TABLE SYSETC (
	SENUM	varchar2(100)	NOT NULL,
	SMNUM	varchar2(100)	NULL,
	SECHECK	varchar2(1)	NULL,
	SENOTE	varchar2(400)	NULL
);

CREATE TABLE COSTOMER (
	CSCODE	varchar2(50)	NOT NULL,
	CSNAME	varchar2(100)	NULL,
	CSNUM	varchar2(100)	NULL,
	CSTEL	varchar2(400)	NULL,
	CSGB	varchar2(400)	NULL,
	CSNOTE	varchar2(400)	NULL
);

CREATE TABLE MATINFO (
	MICODE	varchar2(50)	NOT NULL,
	MINAME	varchar2(100)	NULL,
	MISTAND	number	NULL,
	MIUNIT	number	NULL,
	MISAFE	number	NULL,
	MIMAX	number	NULL,
	MIMIN	number	NULL,
	CCODEID	varchar2(50)	NOT NULL
);

CREATE TABLE BOM (
	BCODE	varchar2(50)	NOT NULL,
	MICODE	varchar2(50)	NOT NULL,
	GICODE	varchar2(50)	NOT NULL,
	BAM	number	NULL,
	BNOTE	varchar2(400)	NULL
);

CREATE TABLE GOODSINFO (
	GICODE	varchar2(50)	NOT NULL,
	GINAME	varchar2(100)	NULL,
	GIUNIT	number	NULL,
	GIIMG	clob	NULL,
	GISAFE	number	NULL,
	GIMAX	number	NULL,
	GIMIN	number	NULL
);

CREATE TABLE ERRINFO (
	EICODEID	varchar2(50)	NOT NULL,
	EINAME	varchar2(100)	NULL
);

CREATE TABLE COMMON (
	CCODEID	varchar2(50)	NOT NULL,
	CCLASS	varchar2(100)	NULL,
	CCLASSD	varchar2(100)	NULL,
	CEXPLAIN	varchar2(400)	NULL,
	CEXPLAIND	varchar2(400)	NULL,
	CNOTE	varchar2(400)	NULL
);

CREATE TABLE PROCINFO (
	PICODEID	varchar2(50)	NOT NULL,
	PINAME	varchar2(100)	NULL,
	PIONE	varchar2(400)	NULL,
	PITWO	varchar2(400)	NULL,
	PITHREE	varchar2(400)	NULL,
	PIFOUR	varchar2(400)	NULL,
	PIDATE	varchar2(400)	NULL
);

CREATE TABLE MATLOT (
	MLNUM	varchar2(100)	NULL,
	MLAM	number	NULL,
	MICODE	varchar2(50)	NOT NULL
);

CREATE TABLE AUTHORITY (
	ACODE	varchar2(50)	NULL,
	ACLASS	varchar2(400)	NULL
);

CREATE TABLE EMPLOYEE (
	ECODE	varchar2(50)	NOT NULL,
	ACODE2	varchar2(50)	NULL,
	EHIREDATE	date	NULL,
	EPOSITION	varchar2(400)	NULL,
	ENAME	varchar2(100)	NULL
);

CREATE TABLE MATSTK (
	Key	varchar2(100)	NOT NULL,
	MICODE	varchar2(50)	NOT NULL,
	MSNUM	varchar2(100)	NOT NULL,
	MSCOAM	number	NULL,
	MSCIAM	number	NULL,
	MSNOTE	varchar2(1000)	NULL
);

CREATE TABLE DELIVER (
	DNUM	varchar2(100)	NOT NULL,
	SHNUM	varchar2(100)	NOT NULL,
	DCODE	varchar2(50)	NULL
);

