DROP TABLE  MATORD;
DROP TABLE  MATSAR;

DROP TABLE  PRODPLAN;
DROP TABLE  PRODPLAN_D;

DROP TABLE  PRODCOMM;
DROP TABLE  PROCCOMM_D;
DROP TABLE  MATREQ;

DROP TABLE  PROCHEAD;
DROP TABLE  PROCHEAD_D;
DROP TABLE  GOODS_ERR;

DROP TABLE  SYSINFO;

DROP TABLE  CONTRACT;
DROP TABLE  PRODREQ;
DROP TABLE  GOODSSTK;

DROP TABLE  SHIP;
DROP TABLE  SYSMAN;

DROP TABLE  SYSETC;
DROP TABLE  COSTOMER;
DROP TABLE  MATINFO;
DROP TABLE  BOM;

DROP TABLE  GOODSINFO;
DROP TABLE  ERRINFO;
DROP TABLE  COMMON;
DROP TABLE  PROCINFO;
DROP TABLE  MATLOT;
DROP TABLE  AUTHORITY;
DROP TABLE  EMPLOYEE;

DROP TABLE  MATSTK;
DROP TABLE  DELIVER;